"""The wide metric view columns

Each entry is (view column, dataset id, metric name, metric_values column to read)
"""

BLOCK_GROUP_COLUMNS: list[tuple[str, str, str, str]] = [
    ('housing_pre_1990_pct_calc', 'age_of_structure',
     'Total Housing Built Before 1990 (calc.)', 'percentage'),
    ('vehicles_aggregate_abs', 'aggregate_vehicles',
     'Aggregate number of vehicles available', 'absolute'),
    ('gender_male_pct', 'genders',
     'Male', 'percentage'),
    ('gender_female_pct', 'genders',
     'Female', 'percentage'),
    ('no_health_insurance_pct_calc', 'health_insurance',
     'No Health Insurance Coverage (calc.)', 'percentage'),
    ('no_computer_pct', 'households_w_computer',
     'No Computer', 'percentage'),
    ('fpl_total_abs', 'income_share_of_fpl',
     'Total', 'absolute'),
    ('fpl_under_100_pct_calc', 'income_share_of_fpl',
     'Total Under 100% FPL (calc.)', 'percentage'),
    ('fpl_under_150_pct_calc', 'income_share_of_fpl',
     'Total Under 150% FPL (calc.)', 'percentage'),
    ('fpl_under_200_pct_calc', 'income_share_of_fpl',
     'Total Under 200% FPL (calc.)', 'percentage'),
    ('fpl_below_100_abs', 'income_share_of_fpl',
     'POVERTY STATUS IN THE PAST 12 MONTHS Population for whom poverty status is determined Below 100 percent of the poverty level', 'absolute'),
    ('fpl_100_to_149_abs', 'income_share_of_fpl',
     'POVERTY STATUS IN THE PAST 12 MONTHS Population for whom poverty status is determined 100 to 149 percent of the poverty level', 'absolute'),
    ('no_internet_pct', 'internet_subscription',
     'No Internet access', 'percentage'),
    ('limited_english_total_pct_calc', 'limited_english_speaking',
     'Total Limited English Speaking Households (calc.)', 'percentage'),
    ('limited_english_spanish_pct', 'limited_english_speaking',
     'Spanish: Limited English speaking household', 'percentage'),
    ('limited_english_indo_european_pct', 'limited_english_speaking',
     'Other Indo-European languages: Limited English speaking household', 'percentage'),
    ('limited_english_asian_pi_pct', 'limited_english_speaking',
     'Asian and Pacific Island languages: Limited English speaking household', 'percentage'),
    ('limited_english_other_pct', 'limited_english_speaking',
     'Other languages: Limited English speaking household', 'percentage'),
    ('living_alone_total_pct_calc', 'living_arrangements',
     'Total Living alone (calc.)', 'percentage'),
    ('living_alone_male_pct', 'living_arrangements',
     'In households: Householder: Male: Living alone', 'percentage'),
    ('living_alone_female_pct', 'living_arrangements',
     'In households: Householder: Female: Living alone', 'percentage'),
    ('females_under_5_pct_calc', 'person_under_5_65_females',
     'Females Under 5 (calc.)', 'percentage'),
    ('females_under_18_pct_calc', 'person_under_5_65_females',
     'Females Under 18 (calc.)', 'percentage'),
    ('females_over_65_pct_calc', 'person_under_5_65_females',
     'Females Over 65 (calc.)', 'percentage'),
    ('males_under_5_pct_calc', 'person_under_5_65_males',
     'Males Under 5 (calc.)', 'percentage'),
    ('males_under_18_pct_calc', 'person_under_5_65_males',
     'Males Under 18 (calc.)', 'percentage'),
    ('males_over_65_pct_calc', 'person_under_5_65_males',
     'Males Over 65 (calc.)', 'percentage'),
    ('group_quarters_total_abs', 'population_group_quarters',
     'Institutionalized population', 'absolute'),
    ('group_quarters_correctional_abs', 'population_group_quarters',
     'Institutionalized population: Correctional facilities for adults', 'absolute'),
    ('group_quarters_juvenile_abs', 'population_group_quarters',
     'Institutionalized population: Juvenile facilities', 'absolute'),
    ('group_quarters_nursing_abs', 'population_group_quarters',
     'Institutionalized population: Nursing facilities/Skilled-nursing facilities', 'absolute'),
    ('group_quarters_other_abs', 'population_group_quarters',
     'Institutionalized population: Other institutional facilities', 'absolute'),
    ('race_white_pct', 'race_origin',
     'White alone', 'percentage'),
    ('race_black_pct', 'race_origin',
     'Black or African American alone', 'percentage'),
    ('race_aian_pct', 'race_origin',
     'American Indian and Alaska Native alone', 'percentage'),
    ('race_asian_pct', 'race_origin',
     'Asian alone', 'percentage'),
    ('race_nhpi_pct', 'race_origin',
     'Native Hawaiian and Other Pacific Islander alone', 'percentage'),
    ('race_other_pct', 'race_origin',
     'Some Other Race alone', 'percentage'),
    ('race_two_or_more_pct', 'race_origin',
     'Two or More Races', 'percentage'),
    ('tenure_renter_pct', 'tenure',
     'Renter occupied', 'percentage'),
]

HAWAIIAN_HOMELAND_COLUMNS: list[tuple[str, str, str, str]] = [
    ('pop_under_5_pct_calc', '2022_census_hawaiian_homelands',
     'Total Population Under 5 (calc.)', 'percentage'),
    ('pop_under_18_pct_calc', '2022_census_hawaiian_homelands',
     'Total Population Under 18 (calc.)', 'percentage'),
    ('pop_over_65_pct_calc', '2022_census_hawaiian_homelands',
     'Total Population Over 65 (calc.)', 'percentage'),
    ('male_pct', '2022_census_hawaiian_homelands',
     'Total population SEX Male', 'percentage'),
    ('female_pct', '2022_census_hawaiian_homelands',
     'Total population SEX Female', 'percentage'),
    ('race_white_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race White', 'percentage'),
    ('race_black_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race Black or African American', 'percentage'),
    ('race_aian_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race American Indian and Alaska Native', 'percentage'),
    ('race_asian_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race Asian', 'percentage'),
    ('race_nhpi_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race Native Hawaiian and Other Pacific Islander', 'percentage'),
    ('race_other_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN One race Some other race', 'percentage'),
    ('race_two_or_more_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN Two or more races', 'percentage'),
    ('hispanic_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN Hispanic or Latino origin (of any race)', 'percentage'),
    ('race_white_non_hispanic_pct', '2022_census_hawaiian_homelands',
     'Total population RACE AND HISPANIC OR LATINO ORIGIN White alone, not Hispanic or Latino', 'percentage'),
    ('limited_english_pct', '2022_census_hawaiian_homelands',
     'LANGUAGE SPOKEN AT HOME AND ABILITY TO SPEAK ENGLISH Population 5 years and over Speak language other than English Speak English less than very well', 'percentage'),
    ('median_income_abs', '2022_census_hawaiian_homelands',
     "INDIVIDUALS' INCOME IN THE PAST 12 MONTHS (IN 2022 INFLATION-ADJUSTED DOLLARS) Population 15 years and over Median income (dollars)", 'absolute'),
]