import { HazardLayerConfig } from "../types";

export const HAZARD_LAYERS: HazardLayerConfig[] = [
  {
    id: "flood_hazard",
    name: "Flooding",
    visible: false,
    icon: "FaWater",
    color: "#0000FF",
    subLayers: [
      {
        id: "Zone_VE",
        name: "Coastal High Risk",
        color: "#0000FF",
        visible: false,
        filePath: "Flood_Hazard_VE.pmtiles",
        popupConfig: {
          titleField: "Coastal High Risk",
          fields: [
            { key: "fld_zone", label: "Flood Zone" },
            { key: "static_bfe", label: "Base Flood Elevation" },
          ],
        },
      },
      {
        id: "Zone_AE",
        name: "Base Flood Area",
        color: "#1313c2",
        visible: false,
        filePath: "Flood_Hazard_AE.pmtiles",
        popupConfig: {
          titleField: "Base Flood Area",
          fields: [
            { key: "fld_zone", label: "Flood Zone" },
            { key: "static_bfe", label: "Base Flood Elevation" },
          ],
        },
      },
      {
        id: "Zone_AO",
        name: "Shallow Sheet Flow",
        color: "#161691",
        visible: false,
        filePath: "Flood_Hazard_AO.pmtiles",
        popupConfig: {
          titleField: "Shallow Sheet Flow",
          fields: [
            { key: "fld_zone", label: "Flood Zone" },
            { key: "depth", label: "Depth" },
          ],
        },
      },
      {
        id: "Zone_AH",
        name: "Shallow Ponding",
        color: "#12126e",
        visible: false,
        filePath: "Flood_Hazard_AH.pmtiles",
        popupConfig: {
          titleField: "Shallow Ponding",
          fields: [
            { key: "fld_zone", label: "Flood Zone" },
            { key: "static_bfe", label: "Base Flood Elevation" },
          ],
        },
      },
      /*
      { id: "full_combined", name: "All Zones (Combined)", color: "#0000FF", visible: false, filePath: "Flood_Hazard.pmtiles", popupConfig: { fields: [{ key: "fld_zone", label: "Flood Zone" }] } },
      { id: "trimmed", name: "All Zones (Trimmed)", color: "#0000FF", visible: false, filePath: "Flood_Hazard_trimmed.pmtiles", popupConfig: {} },
      */
    ],
  },
  {
    id: "erosion",
    name: "Coastal Erosion",
    visible: false,
    icon: "FaUmbrellaBeach",
    color: "#A89C90",
    subLayers: [
      {
        id: "0.5ft_erosion",
        name: "0.5ft",
        color: "#736a62",
        visible: false,
        filePath: "filtered_slr_cstl_erosn_0pt5ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "1.1ft_erosion",
        name: "1.1ft",
        color: "#63584f",
        visible: false,
        filePath: "filtered_slr_cstl_erosn_1pt1ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "2.0ft_erosion",
        name: "2.0ft",
        color: "#5c4e42",
        visible: false,
        filePath: "filtered_slr_cstl_erosn_2pt0ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "3.2ft_erosion",
        name: "3.2ft",
        color: "#524032",
        visible: false,
        filePath: "filtered_slr_cstl_erosn_3pt2ft.pmtiles",
        popupConfig: {},
      },
    ],
  },
  {
    id: "potential_flood_highways",
    name: "Highway Flood Risk",
    visible: false,
    icon: "FaRoad",
    color: "#000000",
    subLayers: [
      {
        id: "0.5ft_pfh",
        name: "0.5ft",
        color: "#000000",
        visible: false,
        filePath: "filtered_slr_potent_fld_hwys_0pt5ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "NAME", label: "Highway" }] },
      },
      {
        id: "1.1ft_pfh",
        name: "1.1ft",
        color: "#2e2e2e",
        visible: false,
        filePath: "filtered_slr_potent_fld_hwys_1pt1ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "NAME", label: "Highway" }] },
      },
      {
        id: "2.0ft_pfh",
        name: "2.0ft",
        color: "#575757",
        visible: false,
        filePath: "filtered_slr_potent_fld_hwys_2pt0ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "NAME", label: "Highway" }] },
      },
      {
        id: "3.2ft_pfh",
        name: "3.2ft",
        color: "#808080",
        visible: false,
        filePath: "filtered_slr_potent_fld_hwys_3pt2ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "NAME", label: "Highway" }] },
      },
    ],
  },
  {
    id: "exposure_area",
    name: "Exposure Area",
    visible: false,
    icon: "FaRadiationAlt",
    color: "#7ea834",
    subLayers: [
      {
        id: "0.5ft_ea",
        name: "0.5ft",
        color: "#7ea834",
        visible: false,
        filePath: "filtered_slr_exposure_area_0pt5ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "1.1ft_ea",
        name: "1.1ft",
        color: "#7ea834",
        visible: false,
        filePath: "filtered_slr_exposure_area_1pt1ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "2.0ft_ea",
        name: "2.0ft",
        color: "#7ea834",
        visible: false,
        filePath: "filtered_slr_exposure_area_2pt0ft.pmtiles",
        popupConfig: {},
      },
      {
        id: "3.2ft_ea",
        name: "3.2ft",
        color: "#7ea834",
        visible: false,
        filePath: "filtered_slr_exposure_area_3pt2ft.pmtiles",
        popupConfig: {},
      },
      /* { id: "3.2ft_ea_scenario", name: "3.2ft Scenario", color: "#7ea834", visible: false, filePath: "filtered_slr_exposure_area_3pt2ft_scenario.pmtiles", popupConfig: {} }, */
    ],
  },
  {
    id: "passive_flood",
    name: "Passive Flood",
    visible: false,
    icon: "FaTint",
    color: "#37bbf0",
    subLayers: [
      {
        id: "0.5ft_pf",
        name: "0.5ft",
        color: "#37bbf0",
        visible: false,
        filePath: "filtered_slr_passive_fld_0pt5ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "FloodSrc", label: "Flood SRC" }] },
      },
      {
        id: "1.1ft_pf",
        name: "1.1ft",
        color: "#2c9cc9",
        visible: false,
        filePath: "filtered_slr_passive_fld_1pt1ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "FloodSrc", label: "Flood SRC" }] },
      },
      {
        id: "2.0ft_pf",
        name: "2.0ft",
        color: "#22799c",
        visible: false,
        filePath: "filtered_slr_passive_fld_2pt0ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "FloodSrc", label: "Flood SRC" }] },
      },
      {
        id: "3.2ft_pf",
        name: "3.2ft",
        color: "#1a5d78",
        visible: false,
        filePath: "filtered_slr_passive_fld_3pt2ft.pmtiles",
        popupConfig: { titleField: "", fields: [{ key: "FloodSrc", label: "Flood SRC" }] },
      },
    ],
  },
  {
    id: "sidewalks_and_paths",
    name: "Sidewalks and Paths",
    visible: false,
    icon: "FaWalking",
    color: "#000000",
    filePath: "filtered_sidewalks_and_paths.pmtiles",
    popupConfig: {
      titleField: "",
      fields: [
        { key: "ISLAND", label: "Island" },
        { key: "TYPE", label: "Type" },
        { key: "MATERIAL", label: "Material" },
      ],
    },
  },
  {
    id: "state_roads",
    name: "State Roads",
    visible: false,
    icon: "FaRoad",
    color: "#000000",
    subLayers: [
      {
        id: "hawaii_island",
        name: "Hawaii Island",
        color: "#000000",
        visible: false,
        filePath: "filtered_road_Hawaii_island.pmtiles",
        popupConfig: {},
      },
      {
        id: "kauai",
        name: "Kauai",
        color: "#000000",
        visible: false,
        filePath: "filtered_road_Kauai.pmtiles",
        popupConfig: {},
      },
      {
        id: "maui",
        name: "Maui",
        color: "#000000",
        visible: false,
        filePath: "filtered_road_Maui.pmtiles",
        popupConfig: {},
      },
      {
        id: "oahu",
        name: "Oahu",
        color: "#000000",
        visible: false,
        filePath: "filtered_road_Oahu.pmtiles",
        popupConfig: {},
      },
    ],
  },
  {
    id: "solar_insolation",
    name: "Solar Insolation",
    visible: false,
    icon: "FaSun",
    color: "#FFD700",
    subLayers: [
      {
        id: "200_250",
        name: "200–250 W/m²",
        color: "#FFE066",
        visible: false,
        filePath: "Solar_Insolation_200-250.pmtiles",
        popupConfig: {},
      },
      {
        id: "250_300",
        name: "250–300 W/m²",
        color: "#FFD700",
        visible: false,
        filePath: "Solar_Insolation_250-300.pmtiles",
        popupConfig: {},
      },
      {
        id: "300_350",
        name: "300–350 W/m²",
        color: "#FFC200",
        visible: false,
        filePath: "Solar_Insolation_300-350.pmtiles",
        popupConfig: {},
      },
      {
        id: "350_400",
        name: "350–400 W/m²",
        color: "#FFAD00",
        visible: false,
        filePath: "Solar_Insolation_350-400.pmtiles",
        popupConfig: {},
      },
      {
        id: "400_450",
        name: "400–450 W/m²",
        color: "#FF9800",
        visible: false,
        filePath: "Solar_Insolation_400-450.pmtiles",
        popupConfig: {},
      },
      {
        id: "450_500",
        name: "450–500 W/m²",
        color: "#FF8300",
        visible: false,
        filePath: "Solar_Insolation_450-500.pmtiles",
        popupConfig: {},
      },
      {
        id: "500_550",
        name: "500–550 W/m²",
        color: "#FF6E00",
        visible: false,
        filePath: "Solar_Insolation_500-550.pmtiles",
        popupConfig: {},
      },
      {
        id: "550_600",
        name: "550–600 W/m²",
        color: "#FF5900",
        visible: false,
        filePath: "Solar_Insolation_550-600.pmtiles",
        popupConfig: {},
      },
      {
        id: "600_650",
        name: "600–650 W/m²",
        color: "#FF4400",
        visible: false,
        filePath: "Solar_Insolation_600-650.pmtiles",
        popupConfig: {},
      },
    ],
  },
  {
    id: "fire_zone",
    name: "Fire Zone",
    visible: false,
    icon: "faFire",
    color: "#D73502",
    subLayers: [
      { 
        id: "Zone_1",
        name: "Zone 1",
        color: "#D73502",
        visible: false,
        filePath: "Fire_zone_1.pmtiles",
        popupConfig: {
          titleField: "Zone 1", 
          fields: [ 
            { key: "commu_name", label: "Community name" }, 
            { key: "island", label: "Island" },
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
      {
        id: "Zone_2",
        name: "Zone 2",
        color: "#FF7500",
        visible: false,
        filePath: "Fire_zone_2.pmtiles",
        popupConfig: {
          titleField: "Zone 2",
          fields: [
            { key: "commu_name", label: "Community name" },
            { key: "island", label: "Island" },
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
      {
        id: "Zone_3",
        name: "Zone 3",
        color: "#F46D43",
        visible: false,
        filePath: "Fire_zone_3.pmtiles",
        popupConfig: {
          titleField: "Zone 3",
          fields: [
            { key: "commu_name", label: "Community name" },  
            { key: "island", label: "Island" }, 
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
      {
        id: "Zone_4",
        name: "Zone 4",
        color: "#FDAE61",
        visible: false,
        filePath: "Fire_zone_4.pmtiles",
        popupConfig: {
          titleField: "Zone 4",
          fields: [
            { key: "commu_name", label: "Community name" },  
            { key: "island", label: "Island" }, 
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
      {
        id: "Zone_5",
        name: "Zone 5",
        color: "#A6D96A",
        visible: false,
        filePath: "Fire_zone_5.pmtiles",
        popupConfig: {
          titleField: "Zone 5",
          fields: [
            { key: "commu_name", label: "Community name" },  
            { key: "island", label: "Island" }, 
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
      {
        id: "Zone_6",
        name: "Zone 6",
        color: "#1A9641",
        visible: false,
        filePath: "Fire_zone_6.pmtiles",
        popupConfig: {
          titleField: "Zone 6",
          fields: [
            { key: "commu_name", label: "Community name" },  
            { key: "island", label: "Island" }, 
            { key: "risk_ratin", label: "Risk Rating" },
          ],
        },
      },
    ],
  }, 
  /*
  {
    id: "potent_econ_loss",
    name: "Potential Economic Loss",
    visible: false,
    icon: "FaDollarSign",
    color: "#8B0000",
    subLayers: [
      { id: "0.5ft_pel", name: "0.5ft", color: "#8B0000", visible: false, filePath: "filtered_slr_potent_econ_loss_0pt5ft.pmtiles", popupConfig: {} },
      { id: "1.1ft_pel", name: "1.1ft", color: "#A00000", visible: false, filePath: "filtered_slr_potent_econ_loss_1pt1ft.pmtiles", popupConfig: {} },
      { id: "2.0ft_pel", name: "2.0ft", color: "#B50000", visible: false, filePath: "filtered_slr_potent_econ_loss_2pt0ft.pmtiles", popupConfig: {} },
      { id: "3.2ft_pel", name: "3.2ft", color: "#CC0000", visible: false, filePath: "filtered_slr_potent_econ_loss_3pt2ft.pmtiles", popupConfig: {} },
    ],
  },
  */
];
