import { PointLayerConfig } from "../types";

export const POINT_LAYERS: PointLayerConfig[] = [
  {
    id: "fire_stations",
    name: "Fire Stations",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaFireExtinguisher",
    color: "#FF0000",
    filePath: "Fire_Stations_(Statewide).geojson",
    idFields: ["objectid"],
    popupConfig: { titleField: "name", fields: [] },
  },
  {
    id: "hospitals",
    name: "Hospitals",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaHospital",
    color: "#00BFFF",
    filePath: "Hospitals.geojson",
    idFields: ["objectid"],
    popupConfig: { titleField: "name", fields: [] },
  },
  {
    id: "police_stations",
    name: "Police Stations",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaShieldAlt",
    color: "#000080",
    filePath: "Police_Stations_(Statewide).geojson",
    idFields: ["objectid"],
    popupConfig: { titleField: "name", fields: [] },
  },
  {
    id: "shelters",
    name: "Emergency Shelters",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaHouseUser",
    color: "#00CC00",
    filePath: "emergency_shelters.geojson",
    // OBJECTID is stamped 0 on 28 shelters; the name is unique on all of them
    idFields: ["BUSNAME"],
    popupConfig: {
      titleField: "BUSNAME",
      fields: [
        { key: "ADDRESS", label: "Address" },
        { key: "PLACENAME", label: "Location" },
      ],
    },
  },
  {
    id: "preschools",
    name: "Preschools",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaSchool",
    color: "#FFA500",
    filePath: "Preschools.geojson",
    idFields: ["objectid"],
    popupConfig: {
      titleField: "name",
      fields: [
        { key: "address", label: "Address" },
        { key: "city", label: "City" },
      ],
    },
  },
  {
    id: "public_schools",
    name: "Public Schools",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaSchool",
    color: "#8A2BE2",
    filePath: "Public_Schools.geojson",
    idFields: ["objectid"],
    popupConfig: {
      titleField: "sch_name",
      fields: [
        { key: "address", label: "Address" },
        { key: "city", label: "City" },
      ],
    },
  },
  {
    id: "private_schools",
    name: "Private Schools",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaSchool",
    color: "#DC143C",
    filePath: "Private_Schools.geojson",
    idFields: ["objectid"],
    popupConfig: {
      titleField: "school",
      fields: [
        { key: "address", label: "Address" },
        { key: "city", label: "City" },
      ],
    },
  },
  {
    id: "bridges",
    name: "Bridges",
    menu: "criticalInfrastructure",
    visible: false,
    icon: "FaArchway",
    color: "#6c757d",
    filePath: "National_Bridge_Inventory.geojson",
    idFields: ["objectid"],
    popupConfig: {
      titleField: "structure_",
      fields: [
        { key: "structure_", label: "Structure ID" },
        { key: "year_built", label: "Year Built" },
        { key: "bridge_con", label: "Bridge Condition" },
      ],
    },
  },
  {
    id: "sewage",
    name: "Sewage Disposal Systems",
    menu: "locationsOfEnhancedExposure",
    visible: false,
    icon: "FaToilet",
    color: "#964B00",
    filePath: "HI_Onsite_Sewage_Disposal_Systems.geojson",
    idFields: ["layer", "objectid"],
    popupConfig: {
      titleField: "island",
      fields: [
        { key: "osds_qty", label: "OSDS Quantity" },
        { key: "ttl_osds", label: "Total OSDS" },
        { key: "rsk_score", label: "Risk Score" },
      ],
    },
  },
  {
    id: "wastewater_plant",
    name: "Wastewater Treatment Plants",
    menu: "locationsOfEnhancedExposure",
    visible: false,
    icon: "FaIndustry",
    color: "#2E8B57",
    filePath: "Wastewater_Treatment_Plants.geojson",
    idFields: ["objectid"],
    popupConfig: {
      titleField: "wwtp_name",
      fields: [
        { key: "county", label: "County" },
      ],
    },
  },
  {
    id: "commercial_harbors_points",
    name: "Commercial Harbors",
    menuGroup: "harbors",
    visible: false,
    icon: "FaShip",
    color: "#002FBF",
    filePath: "HI_commercial_harbors_pt.geojson",
    popupConfig: {
      titleField: "harbor_nam",
      fields: [
        { key: "berth_leng", label: "Dock Length" },
        { key: "year_area", label: "Outdoor Storage Area" },
        { key: "shed_area", label: "Warehouse Area" },
        { key: "channel_de", label: "Channel Depth" },
        { key: "turn_basin", label: "Turning Area" },
      ],
    },
  },
  {
    id: "small_boat_harbors_points",
    name: "Small Boat Harbors",
    menuGroup: "harbors",
    visible: false,
    icon: "FaShip",
    color: "#002FBF",
    filePath: "HI_small_boat_harbor.geojson",
    popupConfig: {
      titleField: "name",
      fields: [
        { key: "acreage", label: "Acreage" },
        { key: "desc1", label: "Description 1" },
        { key: "desc2", label: "Description 2" },
        { key: "desc3", label: "Description 3" },
        { key: "f_berths", label: "Number of Berths" },
        { key: "f_moorings", label: "Number of Moorings" },
        { key: "f_ramps", label: "Number of Ramps" },
        { key: "piers", label: "Piers" },
        { key: "bldgs", label: "On-site Buildings" },
        { key: "sweage_out", label: "Pump-out station available" },
        { key: "utilities", label: "Utilities" },
        { key: "restrooms", label: "Restrooms" },
        { key: "constructe", label: "Constructed" },
        { key: "modified", label: "Modified" },
        { key: "plans1", label: "Plans 1" },
        { key: "plans2", label: "Plans 2" },
        { key: "plans3", label: "Plans 3" },

      ],
    },
  },
  {
    id: "airports",
    name: "Airports",
    menuGroup: "airports",
    visible: false,
    icon: "FaPlane",
    color: "#F4B41A",
    filePath: "HI_airports_pt.geojson",
    popupConfig: {
      titleField: "airport_na",
      fields: [
        { key: "airport_co", label: "Airport Code" },
      ],
    },
  },
];